mutation CreateUser {
  user_insert(data: {id_expr: "auth.uid", email: "user@example.com", displayName: "New User"})
}

mutation UpdateUser($displayName: String!) @auth(level: USER) {
  user_update(key: {id_expr: "auth.uid"}, data: {displayName: $displayName})
}

query GetUser @auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    email
    displayName
  }
}

mutation CreateProject($title: String!, $description: String) @auth(level: USER) {
  project_insert(data: {title: $title, description: $description, owner: {id_expr: "auth.uid"}})
}

mutation UpdateProject($id: UUID!, $title: String) @auth(level: USER) {
  project_update(key: {id: $id}, data: {title: $title})
}

mutation DeleteProject($id: UUID!) @auth(level: USER) {
  project_delete(key: {id: $id})
}

query GetProject($id: UUID!) @auth(level: USER) {
  project(id: $id) {
    title
    description
  }
}

query ListProjects @auth(level: USER) {
  projects(where: {owner: {id: {eq_expr: "auth.uid"}}}) {
    title
    deadline
  }
}

mutation CreateTask($title: String!, $projectId: UUID!, $status: String!) @auth(level: USER) {
  task_insert(data: {title: $title, status: $status, project: {id: $projectId}})
}

mutation UpdateTask($id: UUID!, $status: String!) @auth(level: USER) {
  task_update(key: {id: $id}, data: {status: $status})
}

mutation DeleteTask($id: UUID!) @auth(level: USER) {
  task_delete(key: {id: $id})
}

query GetTask($id: UUID!) @auth(level: USER) {
  task(id: $id) {
    title
    status
    priority
  }
}

query ListTasks($projectId: UUID!) @auth(level: USER) {
  tasks(where: {projectId: {eq: $projectId}}) {
    title
    status
  }
}

mutation CreateProjectMember($projectId: UUID!) @auth(level: USER) {
  projectMember_insert(data: {project: {id: $projectId}, user: {id_expr: "auth.uid"}})
}

mutation DeleteProjectMember($id: UUID!) @auth(level: USER) {
  projectMember_delete(key: {id: $id})
}

query ListProjectMembers($projectId: UUID!) @auth(level: USER) {
  projectMembers(where: {projectId: {eq: $projectId}}) {
    user {
      displayName
    }
  }
}

mutation CreateComment($taskId: UUID!, $content: String!) @auth(level: USER) {
  comment_insert(data: {content: $content, task: {id: $taskId}, user: {id_expr: "auth.uid"}})
}

mutation DeleteComment($id: UUID!) @auth(level: USER) {
  comment_delete(key: {id: $id})
}

query ListComments($taskId: UUID!) @auth(level: USER) {
  comments(where: {taskId: {eq: $taskId}}) {
    content
    user {
      displayName
    }
  }
}