type User @table {
  email: String!
  displayName: String!
  photoUrl: String
}

type Project @table {
  title: String!
  description: String
  deadline: Date
  owner: User!
}

type Task @table {
  title: String!
  status: String!
  dueDate: Date
  priority: Int
  project: Project!
  assignedTo: User
}

type ProjectMember @table {
  project: Project!
  user: User!
}

type Comment @table {
  content: String!
  task: Task!
  user: User!
}